package gui;

import dao.NhanVien_DAO;
import dao.TaiKhoan_DAO;
import entity.ChucVu;
import entity.PhieuDatPhong;
import gui.TrangChu;
import gui.DatPhong;
import gui.QuanLiKhachHang;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

public class Global_Layout_QuanLi extends javax.swing.JFrame {

    NhanVien_DAO nhanVien_dao = new NhanVien_DAO();
    TaiKhoan_DAO taiKhoan_dao = new TaiKhoan_DAO();

    private QuanLiLoaiPhong loaiPhongGUI;
    private DatPhong datPhongGUI;
    private QuanLiPhong phongGUI;
    private TimKiemPhongHat timKiemPhongGUI;

    private QuanLiKhachHang khachHangGUI;
    private TimKiemKhachHang timKiemKhachHangGUI;

    private DatDichVu orderdichVuGUI;
    private TimKiemDichVu timKiemDichVuGUI;

    private QuanLiDichVu dichVuGUI;
    private QuanLiLoaiDichVu loaiDVGUI;
    private QuanLiDonViDichVu donViDichVuGUI;
    private ThongKeDichVu thongKeDVGUI;
    private ThongKeKhachHang thongKeKHGUI;
    private TimKiemNhanVien timKiemNhanVienGUI;
    private QuanLiNhanVien nhanVienGUI;
    private ThongKeDoanhThu thongkeDTGUI;
    private TroGiup troGiupGUI;
    private QuanLiChucVu cvGUI;
    private TrangChu trangChuQLGUI;
    boolean active_CapNhatPhong = false;

    public void setActive_CapNhatPhong(boolean active_CapNhatPhong) {
        this.active_CapNhatPhong = active_CapNhatPhong;
    }

    public void logout() {
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });

    }

    public Global_Layout_QuanLi(String tenQuanLi) {
        initComponents();

        Panel_Content.setLayout(new BorderLayout());

        //this.setSize(1400, 1050);
        this.setExtendedState(MAXIMIZED_BOTH);
        trangChuQLGUI = new TrangChu(tenQuanLi);

        trangChuQLGUI.getBtnLogout().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                logout();
                taiKhoan_dao.capNhatTrangThaiDangNhap(trangChuQLGUI.getTaiKhoan().getText(), 0);

            }

            private void dispose() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });

        RenderLayout(trangChuQLGUI.getpanel_TrangChu());
        this.setLocationRelativeTo(null);
        this.remove(Panel_Content);
        this.add(Panel_Content, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        Panel_Content = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuTrangChu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jmiDatPhong = new javax.swing.JMenuItem();
        jmiOrder = new javax.swing.JMenuItem();
        jmiTraPhong = new javax.swing.JMenuItem();
        jmiQuanLiNhanVien = new javax.swing.JMenuItem();
        jmiTimKiemNhanVien = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuOrder = new javax.swing.JMenu();
        jmiQuanLiDichVU = new javax.swing.JMenuItem();
        jmiQuanLiLoaiDV = new javax.swing.JMenuItem();
        jmiQuanLiDonVi = new javax.swing.JMenuItem();
        jmiTimKiemDV = new javax.swing.JMenuItem();
        MenuKH = new javax.swing.JMenu();
        jmiCapNhatKhach = new javax.swing.JMenuItem();
        jmiTimKiemKhach = new javax.swing.JMenuItem();
        MenuDatPhong = new javax.swing.JMenu();
        jmiQuanLiPhong = new javax.swing.JMenuItem();
        jmiTimKiemPhong = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiHoaDon = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmiThongKeTheoNgay = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Content.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel_ContentMouseMoved(evt);
            }
        });
        Panel_Content.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_ContentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_ContentMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_ContentMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_ContentLayout = new javax.swing.GroupLayout(Panel_Content);
        Panel_Content.setLayout(Panel_ContentLayout);
        Panel_ContentLayout.setHorizontalGroup(
            Panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        Panel_ContentLayout.setVerticalGroup(
            Panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Content, java.awt.BorderLayout.CENTER);

        MenuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/trangchu-icon.png"))); // NOI18N
        MenuTrangChu.setText("Trang chủ");
        MenuTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTrangChuMouseClicked(evt);
            }
        });
        MenuTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTrangChuActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuTrangChu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/NhanVien-icon-24.png"))); // NOI18N
        jMenu1.setText("Nhân Viên");

        jmiDatPhong.setText("Đặt Phòng");
        jmiDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDatPhongActionPerformed(evt);
            }
        });
        jMenu1.add(jmiDatPhong);

        jmiOrder.setText(" Đặt Dịch Vụ");
        jmiOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOrderActionPerformed(evt);
            }
        });
        jMenu1.add(jmiOrder);

        jmiTraPhong.setText("Trả Phòng");
        jmiTraPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTraPhongActionPerformed(evt);
            }
        });
        jMenu1.add(jmiTraPhong);

        jmiQuanLiNhanVien.setText("Quản Lí Nhân Viên");
        jmiQuanLiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLiNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(jmiQuanLiNhanVien);

        jmiTimKiemNhanVien.setText("Tìm kiếm nhân viên");
        jmiTimKiemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTimKiemNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(jmiTimKiemNhanVien);

        jMenuItem3.setText("Quản lí chức vụ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        MenuOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/dichvu-icon.png"))); // NOI18N
        MenuOrder.setText("Dịch vụ");

        jmiQuanLiDichVU.setText("Quản Lí Dịch Vụ");
        jmiQuanLiDichVU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLiDichVUActionPerformed(evt);
            }
        });
        MenuOrder.add(jmiQuanLiDichVU);

        jmiQuanLiLoaiDV.setText("Quản Lí Loại Dịch Vụ");
        jmiQuanLiLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLiLoaiDVActionPerformed(evt);
            }
        });
        MenuOrder.add(jmiQuanLiLoaiDV);

        jmiQuanLiDonVi.setText("Quản lí Đơn Vị");
        jmiQuanLiDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLiDonViActionPerformed(evt);
            }
        });
        MenuOrder.add(jmiQuanLiDonVi);

        jmiTimKiemDV.setText("Tìm kiếm Dịch Vụ");
        jmiTimKiemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTimKiemDVActionPerformed(evt);
            }
        });
        MenuOrder.add(jmiTimKiemDV);

        jMenuBar1.add(MenuOrder);

        MenuKH.setBackground(new java.awt.Color(0, 0, 0));
        MenuKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/KhachHang-icon.png"))); // NOI18N
        MenuKH.setText("Khách hàng");

        jmiCapNhatKhach.setText("Cập nhật khách hàng");
        jmiCapNhatKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCapNhatKhachActionPerformed(evt);
            }
        });
        MenuKH.add(jmiCapNhatKhach);

        jmiTimKiemKhach.setText("Tìm kiếm khách hàng");
        jmiTimKiemKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTimKiemKhachActionPerformed(evt);
            }
        });
        MenuKH.add(jmiTimKiemKhach);

        jMenuBar1.add(MenuKH);

        MenuDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/phong-icon.png"))); // NOI18N
        MenuDatPhong.setText(" Phòng");

        jmiQuanLiPhong.setText("Quản lí phòng");
        jmiQuanLiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuanLiPhongActionPerformed(evt);
            }
        });
        MenuDatPhong.add(jmiQuanLiPhong);

        jmiTimKiemPhong.setText("Tìm kiếm phòng");
        jmiTimKiemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTimKiemPhongActionPerformed(evt);
            }
        });
        MenuDatPhong.add(jmiTimKiemPhong);

        jMenuItem1.setText("Quản lí loại phòng");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuDatPhong.add(jMenuItem1);

        jMenuBar1.add(MenuDatPhong);

        jmiHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/hoaDn-icon.png"))); // NOI18N
        jmiHoaDon.setText("Hóa Đơn");
        jmiHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiHoaDonMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmiHoaDon);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/thongke-icon.png"))); // NOI18N
        jMenu2.setText("Thống Kê");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jmiThongKeTheoNgay.setText("Thống kê doanh thu");
        jmiThongKeTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiThongKeTheoNgayActionPerformed(evt);
            }
        });
        jMenu2.add(jmiThongKeTheoNgay);

        jMenuItem4.setText("Thống kê dịch vụ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Thống kê khách hàng");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons-menuBar/help-icon.png"))); // NOI18N
        jMenu3.setText("Trợ giúp");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });

        jMenuItem2.setText("Hướng dẫn sử dụng");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTrangChuMouseClicked
        this.setActive_CapNhatPhong(false);

        RenderLayout(trangChuQLGUI.getpanel_TrangChu());
    }//GEN-LAST:event_MenuTrangChuMouseClicked

    private void jmiQuanLiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLiPhongActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        phongGUI = new QuanLiPhong();
        RenderLayout(phongGUI.getPnPhong());
    }//GEN-LAST:event_jmiQuanLiPhongActionPerformed

    private void jmiDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDatPhongActionPerformed
        this.setActive_CapNhatPhong(true);
        ;
        datPhongGUI = new DatPhong();
        RenderLayout(datPhongGUI.getContent_DP());

    }//GEN-LAST:event_jmiDatPhongActionPerformed

    private void jmiThongKeTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiThongKeTheoNgayActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        thongkeDTGUI = new ThongKeDoanhThu();
        RenderLayout(thongkeDTGUI.getPnThongKeDT()); // TODO add your handling code here:
    }//GEN-LAST:event_jmiThongKeTheoNgayActionPerformed

    private void jmiTimKiemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTimKiemPhongActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        timKiemPhongGUI = new TimKiemPhongHat();
        RenderLayout(timKiemPhongGUI.getPnPhong());
    }//GEN-LAST:event_jmiTimKiemPhongActionPerformed


    private void jmiTraPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTraPhongActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        RenderLayout(new TraPhong().getPnTraPhong());


    }//GEN-LAST:event_jmiTraPhongActionPerformed

    private void jmiTimKiemKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTimKiemKhachActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        timKiemKhachHangGUI = new TimKiemKhachHang();
        RenderLayout(timKiemKhachHangGUI.getPnTimKiemKhachHang());

    }//GEN-LAST:event_jmiTimKiemKhachActionPerformed

    private void Panel_ContentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ContentMouseExited

    }//GEN-LAST:event_Panel_ContentMouseExited

    private void Panel_ContentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ContentMouseReleased

    }//GEN-LAST:event_Panel_ContentMouseReleased

    private void enableActionMovedPhong() {
        datPhongGUI = new DatPhong();
        RenderLayout(datPhongGUI.getContent_DP());

    }

    private void disableActionMovedPhong() {

    }

    private void enableActionMovedTraPhong() {
        RenderLayout(new TraPhong().getPnTraPhong());
    }

    private void Panel_ContentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ContentMouseMoved

        if (active_CapNhatPhong) {

            enableActionMovedPhong();

        } else {
            disableActionMovedPhong();
        }
    }//GEN-LAST:event_Panel_ContentMouseMoved

    private void jmiQuanLiLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLiLoaiDVActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        loaiDVGUI = new QuanLiLoaiDichVu();
        RenderLayout(loaiDVGUI.getPnLoaiDichVu());
    }//GEN-LAST:event_jmiQuanLiLoaiDVActionPerformed

    private void jmiOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOrderActionPerformed

        this.setActive_CapNhatPhong(false);
        ;
        orderdichVuGUI = new DatDichVu("");
        RenderLayout(orderdichVuGUI.getContent_OrderDV());
    }//GEN-LAST:event_jmiOrderActionPerformed

    private void jmiTimKiemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTimKiemDVActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        timKiemDichVuGUI = new TimKiemDichVu();
        RenderLayout(timKiemDichVuGUI.getPnTimKiemDichVu());
    }//GEN-LAST:event_jmiTimKiemDVActionPerformed

    private void jmiQuanLiDichVUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLiDichVUActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        dichVuGUI = new QuanLiDichVu();
        RenderLayout(dichVuGUI.getPnDichVu());
    }//GEN-LAST:event_jmiQuanLiDichVUActionPerformed

    private void jmiCapNhatKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCapNhatKhachActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        khachHangGUI = new QuanLiKhachHang();
        RenderLayout(khachHangGUI.getContent_KH());
    }//GEN-LAST:event_jmiCapNhatKhachActionPerformed

    private void jmiQuanLiDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLiDonViActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        donViDichVuGUI = new QuanLiDonViDichVu();
        RenderLayout(donViDichVuGUI.getPnDonViDichVu());
    }//GEN-LAST:event_jmiQuanLiDonViActionPerformed

    private void Panel_ContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ContentMouseClicked
        System.out.println("gui.Global_Layout_QuanLi.Panel_ContentMouseClicked()");
    }//GEN-LAST:event_Panel_ContentMouseClicked

    private void MenuTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuTrangChuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setActive_CapNhatPhong(false);
        loaiPhongGUI = new QuanLiLoaiPhong();
        RenderLayout(loaiPhongGUI.getPnLoaiPhong());// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setActive_CapNhatPhong(false);
        troGiupGUI = new TroGiup();
        RenderLayout(troGiupGUI.getPnHelp());
        try {
            File file = new File("src/pdf/test.pdf");
            if (file.exists()) {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(file);
                } else {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.setActive_CapNhatPhong(false);
        thongKeDVGUI = new ThongKeDichVu();
        RenderLayout(thongKeDVGUI.getPnThongKeDV());    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.setActive_CapNhatPhong(false);
        thongKeKHGUI = new ThongKeKhachHang();
        RenderLayout(thongKeKHGUI.getPnThongKeKH()); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmiHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiHoaDonMouseClicked

        QuanLiHoaDon QLHoaDon = new QuanLiHoaDon();

        RenderLayout(QLHoaDon.getPnTraPhong());


    }//GEN-LAST:event_jmiHoaDonMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setActive_CapNhatPhong(false);
        cvGUI = new QuanLiChucVu();
        RenderLayout(cvGUI.getPnChucVu());// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmiTimKiemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTimKiemNhanVienActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        timKiemNhanVienGUI = new TimKiemNhanVien();
        RenderLayout(timKiemNhanVienGUI.getPnTimKiemNhanVien());
    }//GEN-LAST:event_jmiTimKiemNhanVienActionPerformed

    private void jmiQuanLiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuanLiNhanVienActionPerformed
        this.setActive_CapNhatPhong(false);
        ;
        nhanVienGUI = new QuanLiNhanVien();
        RenderLayout(nhanVienGUI.getPnQuanLiNhanVien());
    }//GEN-LAST:event_jmiQuanLiNhanVienActionPerformed

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Global_Layout_QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Global_Layout_QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Global_Layout_QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Global_Layout_QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Global_Layout_QuanLi("qlThanhDat").setVisible(true);
            }
        });
    }

    public void RenderLayout(JPanel GUI) {

        Panel_Content.removeAll();
        JPanel pn = GUI;
        Panel_Content.add(pn, BorderLayout.CENTER);
        Panel_Content.setVisible(false);

        Panel_Content.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuDatPhong;
    private javax.swing.JMenu MenuKH;
    private javax.swing.JMenu MenuOrder;
    private javax.swing.JMenu MenuTrangChu;
    private javax.swing.JPanel Panel_Content;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jmiCapNhatKhach;
    private javax.swing.JMenuItem jmiDatPhong;
    private javax.swing.JMenu jmiHoaDon;
    private javax.swing.JMenuItem jmiOrder;
    private javax.swing.JMenuItem jmiQuanLiDichVU;
    private javax.swing.JMenuItem jmiQuanLiDonVi;
    private javax.swing.JMenuItem jmiQuanLiLoaiDV;
    private javax.swing.JMenuItem jmiQuanLiNhanVien;
    private javax.swing.JMenuItem jmiQuanLiPhong;
    private javax.swing.JMenuItem jmiThongKeTheoNgay;
    private javax.swing.JMenuItem jmiTimKiemDV;
    private javax.swing.JMenuItem jmiTimKiemKhach;
    private javax.swing.JMenuItem jmiTimKiemNhanVien;
    private javax.swing.JMenuItem jmiTimKiemPhong;
    private javax.swing.JMenuItem jmiTraPhong;
    // End of variables declaration//GEN-END:variables
}
