/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooser;
import dao.ThongKe_DAO;
import entity.ThongKe;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author HP
 */
public class ThongKeDoanhThu extends javax.swing.JFrame {

    private JPanel pnThongKeNgay;
    private JPanel pnThongKeThang;
    private JPanel pnThongKeNam;
    private QuanLiDichVu qldvGUI;
    private SimpleDateFormat fm = new SimpleDateFormat("dd-MM-yyyy");
    private DefaultTableModel mdlThongKe;
    
    /**
     *
     *
     * Creates new form ThongKeDoanhThu
     */
    public ThongKeDoanhThu() {
        initComponents();
//        jTabbedPane2.addTab("Theo ngày", pnThongKeThang);
//        jTabbedPane2.addTab("Theo tháng", pnThongKeThang);
//        jTabbedPane2.addTab("Theo năm", pnThongKeNam);
   
        new Thread(() -> {
            jdateBDNgay.setDate(new java.util.Date());
        }).start();
        txtNgayHienTai.setText(fm.format(new java.util.Date()));
        this.mdlThongKe = (DefaultTableModel) tblThongKe.getModel();
        pnBieuDoThang.setLayout(new BorderLayout());
        pnBieuDoNam.setLayout(new BorderLayout());
        pnBDThang.add(pnBieuDoThang);
        pnBDNam.add(pnBieuDoNam);
        
    }

    public JPanel getPnThongKeDT() {
        return pnThongKeDT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongKeDT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnThongKe = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnNgay = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbTongHoaDon = new javax.swing.JLabel();
        jdateBDNgay = new com.toedter.calendar.JDateChooser();
        lbTongDT = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        lbNgayHienTai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtNgayHienTai = new javax.swing.JLabel();
        txtTongHoaDon = new javax.swing.JLabel();
        txtTongDoanhThu = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnThang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbChonThang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnBDThang = new javax.swing.JPanel();
        pnBieuDoThang = new javax.swing.JPanel();
        txtTongHoaDonThang = new javax.swing.JLabel();
        txtTongDTThang = new javax.swing.JLabel();
        pnNam = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jboChonNam = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTongHDNam = new javax.swing.JLabel();
        txtTongDTNam = new javax.swing.JLabel();
        pnBDNam = new javax.swing.JPanel();
        pnBieuDoNam = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setText("Thống kê");

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jLabel2.setText("Thống kê doanh thu theo ngày:");

        lbTongHoaDon.setText("Tổng hóa đơn:");

        jdateBDNgay.setDateFormatString("yyyy-MM-dd");
        jdateBDNgay.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jdateBDNgayAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jdateBDNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdateBDNgayPropertyChange(evt);
            }
        });

        lbTongDT.setText("Tổng doanh thu trong ngày:");

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã phòng", "Giờ vào", "Giờ ra", "Tổng giờ sử dụng", "Tổng tiền"
            }
        ));
        jScrollPane2.setViewportView(tblThongKe);

        lbNgayHienTai.setText("Ngày hiện tại:");

        jLabel3.setText("jLabel3");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jButton1.setText("jButton1");

        jButton2.setText("Xuất file Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNgayLayout = new javax.swing.GroupLayout(pnNgay);
        pnNgay.setLayout(pnNgayLayout);
        pnNgayLayout.setHorizontalGroup(
            pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNgayLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdateBDNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNgayLayout.createSequentialGroup()
                        .addComponent(lbTongHoaDon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongHoaDon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNgayHienTai)
                    .addComponent(lbTongDT))
                .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNgayLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtNgayHienTai))
                    .addGroup(pnNgayLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(txtTongDoanhThu)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNgayLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNgayLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNgayLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnNgayLayout.setVerticalGroup(
            pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNgayLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNgayLayout.createSequentialGroup()
                        .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNgayHienTai)
                            .addComponent(txtNgayHienTai))
                        .addGap(18, 18, 18)
                        .addComponent(lbTongDT))
                    .addGroup(pnNgayLayout.createSequentialGroup()
                        .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jdateBDNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTongHoaDon)
                            .addComponent(txtTongHoaDon)
                            .addComponent(txtTongDoanhThu))))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(128, 128, 128))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNgayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Theo ngày", pnNgay);

        jLabel5.setText("Thống kê doanh thu theo tháng của năm nay");

        jLabel6.setText("Tháng");

        jcbChonThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jcbChonThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbChonThangActionPerformed(evt);
            }
        });

        jLabel8.setText("Tổng hóa đơn:");

        jLabel10.setText("Tổng doanh thu trong tháng:");

        javax.swing.GroupLayout pnBieuDoThangLayout = new javax.swing.GroupLayout(pnBieuDoThang);
        pnBieuDoThang.setLayout(pnBieuDoThangLayout);
        pnBieuDoThangLayout.setHorizontalGroup(
            pnBieuDoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1293, Short.MAX_VALUE)
        );
        pnBieuDoThangLayout.setVerticalGroup(
            pnBieuDoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBDThangLayout = new javax.swing.GroupLayout(pnBDThang);
        pnBDThang.setLayout(pnBDThangLayout);
        pnBDThangLayout.setHorizontalGroup(
            pnBDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1416, Short.MAX_VALUE)
            .addGroup(pnBDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnBDThangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnBieuDoThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );
        pnBDThangLayout.setVerticalGroup(
            pnBDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(pnBDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnBDThangLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(pnBieuDoThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnThangLayout = new javax.swing.GroupLayout(pnThang);
        pnThang.setLayout(pnThangLayout);
        pnThangLayout.setHorizontalGroup(
            pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThangLayout.createSequentialGroup()
                .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addGroup(pnThangLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbChonThang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnThangLayout.createSequentialGroup()
                        .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnThangLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTongHoaDonThang))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongDTThang)))
                .addGap(0, 1075, Short.MAX_VALUE))
            .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThangLayout.createSequentialGroup()
                    .addComponent(pnBDThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnThangLayout.setVerticalGroup(
            pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbChonThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTongHoaDonThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTongDTThang))
                .addContainerGap(660, Short.MAX_VALUE))
            .addGroup(pnThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThangLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(pnBDThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Theo tháng", pnThang);

        jLabel9.setText("Năm");

        jboChonNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2017" }));
        jboChonNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboChonNamActionPerformed(evt);
            }
        });

        jLabel11.setText("Tổng hóa đơn:");

        jLabel12.setText("Tổng doanh thu trong năm:");

        javax.swing.GroupLayout pnBieuDoNamLayout = new javax.swing.GroupLayout(pnBieuDoNam);
        pnBieuDoNam.setLayout(pnBieuDoNamLayout);
        pnBieuDoNamLayout.setHorizontalGroup(
            pnBieuDoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1453, Short.MAX_VALUE)
        );
        pnBieuDoNamLayout.setVerticalGroup(
            pnBieuDoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBDNamLayout = new javax.swing.GroupLayout(pnBDNam);
        pnBDNam.setLayout(pnBDNamLayout);
        pnBDNamLayout.setHorizontalGroup(
            pnBDNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnBDNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBDNamLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnBieuDoNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnBDNamLayout.setVerticalGroup(
            pnBDNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(pnBDNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnBieuDoNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNamLayout = new javax.swing.GroupLayout(pnNam);
        pnNam.setLayout(pnNamLayout);
        pnNamLayout.setHorizontalGroup(
            pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNamLayout.createSequentialGroup()
                .addGroup(pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNamLayout.createSequentialGroup()
                        .addGroup(pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNamLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnNamLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTongHDNam))
                                    .addGroup(pnNamLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTongDTNam))))
                            .addGroup(pnNamLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jboChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 999, Short.MAX_VALUE))
                    .addComponent(pnBDNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnNamLayout.setVerticalGroup(
            pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jboChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTongHDNam, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTongDTNam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBDNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Theo năm", pnNam);

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343)
                .addComponent(jLabel7)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnThongKeDTLayout = new javax.swing.GroupLayout(pnThongKeDT);
        pnThongKeDT.setLayout(pnThongKeDTLayout);
        pnThongKeDTLayout.setHorizontalGroup(
            pnThongKeDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeDTLayout.createSequentialGroup()
                .addGroup(pnThongKeDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongKeDTLayout.createSequentialGroup()
                        .addGap(623, 623, 623)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThongKeDTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongKeDTLayout.setVerticalGroup(
            pnThongKeDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeDTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnThongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnThongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbChonThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbChonThangActionPerformed
      
        thongKeThang();        // TODO add your handling code here:
    }//GEN-LAST:event_jcbChonThangActionPerformed

    private void jboChonNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboChonNamActionPerformed
        thongKeNam();        // TODO add your handling code here:
    }//GEN-LAST:event_jboChonNamActionPerformed

    private void jdateBDNgayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jdateBDNgayAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jdateBDNgayAncestorAdded

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void jdateBDNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdateBDNgayPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            if (jdateBDNgay.getDate().after(new java.util.Date())) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày <= ngày hiện tại");
            } else {
                java.sql.Date date = new java.sql.Date(jdateBDNgay.getDate().getTime());
                thongKeNgay(date);
            } // TODO add your handling code here:
    }                                          
    }//GEN-LAST:event_jdateBDNgayPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        xuatFileExcel();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeDoanhThu().setVisible(true);
            }
        });
    }

    private void thongKeThang() {
           
        String thang = (String) jcbChonThang.getSelectedItem();
        ArrayList<entity.ThongKe> list = tk_dao.thongKeThang(thang);
        long tt = 0;
        for (entity.ThongKe tk : list) {
            tt += tk.getTongTien();
        }
        txtTongDTThang.setText(String.valueOf(tt) + " đ");
        txtTongHoaDonThang.setText(String.valueOf(list.size()));
        System.out.println(list.size());
        ChartPanel chartPanel = new ChartPanel(createChartThang(thang));
        pnBieuDoThang.repaint();
        pnBieuDoThang.removeAll();
        pnBieuDoThang.add(chartPanel);

    }

    private void thongKeNam() {
        String nam = (String) jboChonNam.getSelectedItem();
        ArrayList<entity.ThongKe> list = tk_dao.thongKeNam(nam);
        long tt = 0;
        for (entity.ThongKe tk : list) {
            tt += tk.getTongTien();
        }
        txtTongDTNam.setText(String.valueOf(tt) + " đ");
        txtTongHDNam.setText(String.valueOf(list.size()));
        System.out.println(list.size());
        ChartPanel chartPanel = new ChartPanel(createChartNam(nam));
        pnBieuDoNam.repaint();
        pnBieuDoNam.removeAll();
        pnBieuDoNam.add(chartPanel);

    }

    //Biểu đồ doanh thu theo tháng
    private JFreeChart createChartThang(String thang) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 1; i < 32; i++) {
            String ngay = String.valueOf(i);
            long tt = 0;
            ArrayList<entity.ThongKe> list = tk_dao.thongKeNgayThang(thang, ngay);
            for (entity.ThongKe tk : list) {
                tt += tk.getTongTien();
            }
            dataset.addValue(tt, "Tổng tiền", ngay);
        }
        JFreeChart barChart = ChartFactory.createBarChart("BIỂU ĐỒ DOANH THU TRONG THÁNG " + thang, "Ngày",
                "Tổng tiền (VND)", dataset, PlotOrientation.VERTICAL, false, false, false);
        return barChart;
    }

    //Biểu đồ doanh thu theo tháng
    private JFreeChart createChartNam(String nam) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 1; i < 13; i++) {
            String thang = String.valueOf(i);
            long tt = 0;
            ArrayList<entity.ThongKe> list = tk_dao.thongKeThangNam(nam, thang);
            for (entity.ThongKe tk : list) {
                tt += tk.getTongTien();
            }
            dataset.addValue(tt, "Tổng tiền", thang);
        }
        JFreeChart barChart = ChartFactory.createBarChart("BIỂU ĐỒ DOANH THU TRONG NĂM " + nam, "Tháng",
                "Tổng tiền (VND)", dataset, PlotOrientation.VERTICAL, false, false, false);
        return barChart;
    }

    private void thongKeNgay(Date ngay) {
        SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        String ngayStr = fmt.format(ngay);
        ArrayList<entity.ThongKe> list = tk_dao.thongKeNgay(ngayStr);
        if (list.size() > 0) {
            long tt = 0;
            for (entity.ThongKe hd : list) {
                tt += hd.getTongTien();
            }
            txtTongDoanhThu.setText(String.valueOf(tt));
            txtTongHoaDon.setText(String.valueOf(list.size()));

            mdlThongKe.getDataVector().removeAllElements();
            mdlThongKe.fireTableDataChanged();

            for (entity.ThongKe t : list) {
                DecimalFormat fm = new DecimalFormat("#,###.## " + "VND");
                String tongTien = fm.format(t.getTongTien());
                mdlThongKe.addRow(new Object[]{t.getMaHD(), t.getMaPhong(), t.getGioVao(), t.getGioRa(), t.getTongSoGioSD(), tongTien});
            }
        } else {
            mdlThongKe.getDataVector().removeAllElements();
            mdlThongKe.fireTableDataChanged();
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để thống kê");
        }
    }

    private void xuatFileExcel() {
        int rowCount = tblThongKe.getRowCount();
        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để xuất thống kê!");
            return;
        }
        JFileChooser fChooser = new JFileChooser();

        fChooser.addChoosableFileFilter(new FileFilter() {

            @Override
            public String getDescription() {
                // TODO Auto-generated method stub
                return "Excell file (*.xls, *xlsx)";
            }

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".xls") || f.getName().toLowerCase().endsWith(".xlsx");
                }
            }

        });

        int i = fChooser.showSaveDialog(this);
        if (i == 0) {
            String path = fChooser.getSelectedFile().getAbsolutePath();
            if (!path.matches("(.)+(\\.xls|\\.xlsx)$")) {
                path += ".xlsx";
            }
            boolean t = ghiFileExcel(path);

            if (t) {
                JOptionPane.showMessageDialog(null, "Xuất file thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Xuất file không thành công");
            }
        }
    }

    public boolean ghiFileExcel(String path) {
        Workbook workBook = new XSSFWorkbook();

        Sheet sh = workBook.createSheet("Sheet1");
        String header[] = {"Ngày Xuất", "STT", "Mã Hóa Đơn", "Mã phòng", "Giờ vào", "Giờ ra", "Tổng giờ sử dụng", "Tổng Tiền", "Doanh thu trong ngày", "Tổng số hóa đơn"};

        Row rowHeader = sh.createRow(0);
        for (int i = 0; i < header.length; i++) {
            Cell cell = rowHeader.createCell(i);
            cell.setCellValue(header[i]);
        }

        int numRow = 1;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Row row = sh.createRow(numRow++);
        int stt = 1;
        row.createCell(0).setCellValue(df.format(jdateBDNgay.getDate()));
        row.createCell(1).setCellValue(stt);
        row.createCell(2).setCellValue(tblThongKe.getValueAt(0, 0).toString());
        row.createCell(3).setCellValue(tblThongKe.getValueAt(0, 1).toString());
        row.createCell(4).setCellValue(tblThongKe.getValueAt(0, 2).toString());
        row.createCell(5).setCellValue(tblThongKe.getValueAt(0, 3).toString());
        row.createCell(6).setCellValue(tblThongKe.getValueAt(0, 4).toString());
        row.createCell(7).setCellValue(tblThongKe.getValueAt(0, 5).toString());
        row.createCell(8).setCellValue(txtTongDoanhThu.getText().trim());
        row.createCell(9).setCellValue(txtTongHoaDon.getText().trim());
        int rowCount = tblThongKe.getRowCount();
        for (int i = 1; i < rowCount; i++) {
            row = sh.createRow(numRow++);
            stt++;
            row.createCell(1).setCellValue(stt);
            row.createCell(2).setCellValue(tblThongKe.getValueAt(i, 0).toString());
            row.createCell(3).setCellValue(tblThongKe.getValueAt(i, 1).toString());
            row.createCell(4).setCellValue(tblThongKe.getValueAt(i, 2).toString());
            row.createCell(5).setCellValue(tblThongKe.getValueAt(i, 3).toString());
            row.createCell(6).setCellValue(tblThongKe.getValueAt(i, 4).toString());
            row.createCell(7).setCellValue(tblThongKe.getValueAt(i, 5).toString());
        }

        for (int i = 0; i < header.length; i++) {
            sh.autoSizeColumn(i);
        }

        try {
            FileOutputStream f = new FileOutputStream(path);
            workBook.write(f);
            f.close();
            workBook.close();
        } catch (Exception e) {
            return false;
        }
        return true;

    }
    private ThongKe_DAO tk_dao = new ThongKe_DAO();
    ArrayList<ThongKe> dstk = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jboChonNam;
    private javax.swing.JComboBox<String> jcbChonThang;
    private com.toedter.calendar.JDateChooser jdateBDNgay;
    private javax.swing.JLabel lbNgayHienTai;
    private javax.swing.JLabel lbTongDT;
    private javax.swing.JLabel lbTongHoaDon;
    private javax.swing.JPanel pnBDNam;
    private javax.swing.JPanel pnBDThang;
    private javax.swing.JPanel pnBieuDoNam;
    private javax.swing.JPanel pnBieuDoThang;
    private javax.swing.JPanel pnNam;
    private javax.swing.JPanel pnNgay;
    private javax.swing.JPanel pnThang;
    private javax.swing.JPanel pnThongKe;
    private javax.swing.JPanel pnThongKeDT;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JLabel txtNgayHienTai;
    private javax.swing.JLabel txtTongDTNam;
    private javax.swing.JLabel txtTongDTThang;
    private javax.swing.JLabel txtTongDoanhThu;
    private javax.swing.JLabel txtTongHDNam;
    private javax.swing.JLabel txtTongHoaDon;
    private javax.swing.JLabel txtTongHoaDonThang;
    // End of variables declaration//GEN-END:variables
}
