/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.DichVu_DAO;
import dao.DonVi_DAO;
import dao.LoaiDichVu_DAO;
import entity.DichVu;
import entity.DonViDichVu;
import entity.LoaiDichVu;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TimKiemDichVu extends javax.swing.JFrame {

    private DichVu_DAO dv_dao;
    private DonVi_DAO donvi_dao;
    private LoaiDichVu_DAO ldv_dao;
    private ArrayList<DichVu> dsdv;
    private ArrayList<DonViDichVu> dsDonVi;
    private ArrayList<LoaiDichVu> dsLoai;
    private DefaultTableModel mdlTimDV;

    /**
     * Creates new form TimKiemDichVu
     */
    public TimKiemDichVu() {
        initComponents();
        this.mdlTimDV = (DefaultTableModel) tblTimDV.getModel();
        dv_dao = new DichVu_DAO();
        donvi_dao = new DonVi_DAO();
        ldv_dao = new LoaiDichVu_DAO();
        dsdv = dv_dao.getAllDichVu();
        dsLoai = ldv_dao.getAllLoaiDichVu();
        for (LoaiDichVu ldv : dsLoai) {
            cboLoaiDV.addItem(ldv.getTenLoaiDichVu());
        }

        //DocDuLieuVaoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTimKiemDichVu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTimDV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTimDV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cboDonVi = new javax.swing.JComboBox<>();
        cboLoaiDV = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng hát", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N

        tblTimDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Số lượng tồn", "Đơn giá", "Đơn vị"
            }
        ));
        jScrollPane2.setViewportView(tblTimDV);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Tìm kiếm dịch vụ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Tên dịch vụ:");

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons_global/search-16.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Loại dịch vụ:");

        cboDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDonViActionPerformed(evt);
            }
        });

        cboLoaiDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cboLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiDVActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Đơn vị dịch vụ:");

        javax.swing.GroupLayout pnTimKiemDichVuLayout = new javax.swing.GroupLayout(pnTimKiemDichVu);
        pnTimKiemDichVu.setLayout(pnTimKiemDichVuLayout);
        pnTimKiemDichVuLayout.setHorizontalGroup(
            pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemDichVuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTimKiemDichVuLayout.createSequentialGroup()
                        .addGroup(pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTimDV)
                                .addComponent(cboLoaiDV, 0, 126, Short.MAX_VALUE))))
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemDichVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(448, 448, 448))
        );
        pnTimKiemDichVuLayout.setVerticalGroup(
            pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemDichVuLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(47, 47, 47)
                .addGroup(pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(pnTimKiemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnTimKiemDichVuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.getAccessibleContext().setAccessibleName("Danh sách dịch vụ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTimKiemDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnTimKiemDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        mdlTimDV.getDataVector().removeAllElements();
        timDichVu();// TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void cboDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDonViActionPerformed
        try {
             String tenDonVi = cboDonVi.getSelectedItem().toString();
        int maDonVi = donvi_dao.getMaDonViByTenDonVi(tenDonVi);
        ArrayList<DichVu> ds = dv_dao.getListDichVuByMaDonVi(maDonVi);
        if (ds.size() <= 0 ||tenDonVi.equals("")) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy");
        } else {
            mdlTimDV.getDataVector().removeAllElements();
            DocDuLieuVaoTable(ds);

        }
        } catch (NullPointerException e) {
            System.out.println("");
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDonViActionPerformed

    private void cboLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiDVActionPerformed
        cboDonVi.removeAllItems();
        String tenLoai = cboLoaiDV.getSelectedItem().toString().trim();
        //System.out.println(loaidv_dao.getMaByTenLoaiDichVu(tenLoai));
        ArrayList<DonViDichVu> dsDV = donvi_dao.getTenDonViByMaLoai(ldv_dao.getMaByTenLoaiDichVu(tenLoai));
        // System.out.println(dsDV);
        cboDonVi.addItem("");
        for (DonViDichVu dvDichVu : dsDV) {
            cboDonVi.addItem(dvDichVu.getTenDonVi());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiDVActionPerformed

    public JPanel getPnTimKiemDichVu() {
        return pnTimKiemDichVu;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiemDichVu().setVisible(true);
            }
        });
    }

    private void timDichVu() {
        if (validDataTim()) {
            String tenDV = txtTimDV.getText().trim();
            ArrayList<DichVu> ds = dv_dao.getListDichVuByName(tenDV);
            if (ds.size() <= 0) {
                JOptionPane.showMessageDialog(txtTimDV, "Không tìm thấy tên " + tenDV);
            } else {
                DocDuLieuVaoTable(ds);
            }
        }
    }

    private boolean validDataTim() {
        String tenDV = txtTimDV.getText().trim();
        if (!(tenDV.length() > 0)) {
            JOptionPane.showMessageDialog(txtTimDV, "Lỗi: Tên không được để trống");
            return false;
        }
        return true;
    }

    private void DocDuLieuVaoTable(ArrayList<DichVu> dsdv) {
        if (dsdv == null || dsdv.size() <= 0) {
            return;
        }
        DecimalFormat df = new DecimalFormat("#,###.##" + " VND");
        for (DichVu item : dsdv) {
            String donGia = df.format(item.getDonGia());
            mdlTimDV.addRow(new Object[]{item.getMaDichVu(), item.getTenDichVu(), item.getSoLuongTon(), item.getDonGia(), donvi_dao.getTenDonViByMaDonVi(item.getDonVi().getMaDonVi())});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cboDonVi;
    private javax.swing.JComboBox<String> cboLoaiDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnTimKiemDichVu;
    private javax.swing.JTable tblTimDV;
    private javax.swing.JTextField txtTimDV;
    // End of variables declaration//GEN-END:variables
}
