/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import connect.Connect;
import dao.ChucVu_DAO;
import dao.NhanVien_DAO;
import entity.NhanVien;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TimKiemNhanVien extends javax.swing.JFrame {

    private NhanVien_DAO nv_dao;
    private ArrayList<NhanVien> dsnv;
    private DefaultTableModel mdlNV;
    private ChucVu_DAO cv_dao = new ChucVu_DAO();
    private ButtonGroup rdGroup = new ButtonGroup();

    /**
     * Creates new form TimKiemNV
     */
    public TimKiemNhanVien() {
        initComponents();
        rdGroup.add(rdTatCa);
        rdGroup.add(rdGioiTinh);
        rdGroup.add(rdChucVu);
        new Thread(() -> {
            dateNgaySinh.setDate(null);
        }).start();
        Connect.getInstance().getConnection(); // TODO Auto-generated catch block
        this.mdlNV = new DefaultTableModel();
        mdlNV = (DefaultTableModel) tblTimNV.getModel();
        nv_dao = new NhanVien_DAO();
        dsnv = nv_dao.getAllNV();
    }

    public JPanel getPnTimKiemNhanVien() {
        return pnTimKiemNhanVien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTimKiemNhanVien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbTenNV = new javax.swing.JLabel();
        lbdiaChi = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        txtdiaChi = new javax.swing.JTextField();
        lbngaySinh = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        rdTatCa = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rdGioiTinh = new javax.swing.JRadioButton();
        lblChucVu = new javax.swing.JLabel();
        rdChucVu = new javax.swing.JRadioButton();
        cboLoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimNV = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Tìm kiếm nhân viên");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        lbTenNV.setText("Tên nhân viên:");

        lbdiaChi.setText("Địa chỉ:");

        lbngaySinh.setText("Ngày sinh:");

        lbSDT.setText("SDT:");

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        dateNgaySinh.setDateFormatString("dd-MM-yyyy");
        dateNgaySinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateNgaySinhMouseClicked(evt);
            }
        });
        dateNgaySinh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateNgaySinhPropertyChange(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons_global/search-16.png"))); // NOI18N
        jButton12.setText("Tìm");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons_global/Reset-icon.png"))); // NOI18N
        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbdiaChi)
                            .addComponent(lbTenNV)
                            .addComponent(lbngaySinh)
                            .addComponent(lbSDT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNV)
                            .addComponent(txtdiaChi)
                            .addComponent(txtSDT)
                            .addComponent(dateNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addComponent(jButton12)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addGap(78, 78, 78))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenNV)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdiaChi)
                    .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbngaySinh)
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên"));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tất cả");

        rdTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTatCaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Giới tính");

        rdGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGioiTinhActionPerformed(evt);
            }
        });

        lblChucVu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblChucVu.setText(" Chức vụ");

        rdChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdChucVuActionPerformed(evt);
            }
        });

        cboLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocActionPerformed(evt);
            }
        });

        tblTimNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Địa chỉ", "Ngày sinh ", "Số điện thoại", "Chức vụ ", "Giới tính"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTimNV);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Lọc");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdTatCa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdGioiTinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdChucVu)
                .addGap(35, 35, 35)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(rdTatCa)
                            .addComponent(rdChucVu)
                            .addComponent(rdGioiTinh)
                            .addComponent(lblChucVu)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnTimKiemNhanVienLayout = new javax.swing.GroupLayout(pnTimKiemNhanVien);
        pnTimKiemNhanVien.setLayout(pnTimKiemNhanVienLayout);
        pnTimKiemNhanVienLayout.setHorizontalGroup(
            pnTimKiemNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemNhanVienLayout.createSequentialGroup()
                .addGap(509, 509, 509)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnTimKiemNhanVienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimKiemNhanVienLayout.setVerticalGroup(
            pnTimKiemNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemNhanVienLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTimKiemNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTimKiemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTimKiemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void dateNgaySinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateNgaySinhMouseClicked

    }//GEN-LAST:event_dateNgaySinhMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        mdlNV.getDataVector().removeAllElements();
        if (txtTenNV.getText().trim().length() != 0) {
            txtSDT.setText("");
            txtdiaChi.setText("");
            dateNgaySinh.setDate(null);
            timNhanVienTheoTen();
        } else if (txtdiaChi.getText().trim().length() != 0) {
            txtSDT.setText("");
            txtTenNV.setText("");
            dateNgaySinh.setDate(null);
            timNhanVienTheoDiaChi();
        } else if (txtSDT.getText().trim().length() != 0) {
            txtTenNV.setText("");
            txtdiaChi.setText("");
            dateNgaySinh.setDate(null);
            timNhanVienTheoSDT();
        } else {

            if (dateNgaySinh.getDate().after(new java.util.Date())) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày <= ngày hiện tại");
            } else {
                java.sql.Date date = new java.sql.Date(dateNgaySinh.getDate().getTime());
                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                 String ngayStr = fmt.format(date);
                ArrayList<NhanVien> dsns=nv_dao.getListNhanVienByNgaySinh(ngayStr);
                if(!(dsns.size()<=0)){
                DocDuLieuVaoTable(dsns);
                }else
                {
                    JOptionPane.showMessageDialog(null,"Không tìm thấy");
                }
            } // TODO add your handling code here:
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void rdTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTatCaActionPerformed
        resetCbo();
        mdlNV.getDataVector().removeAllElements();
        DocDuLieuVaoTable(dsnv);// TODO add your handling code here:
    }//GEN-LAST:event_rdTatCaActionPerformed

    private void rdGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGioiTinhActionPerformed
        resetCbo();
        loadCombobox("Nam");
        loadCombobox("Nữ");
        // TODO add your handling code here:
    }//GEN-LAST:event_rdGioiTinhActionPerformed

    private void rdChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdChucVuActionPerformed
        resetCbo();
        emptyTable();
        loadChucVu();        // TODO add your handling code here:
    }//GEN-LAST:event_rdChucVuActionPerformed

    private void cboLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocActionPerformed
        emptyTable();
        if (rdGioiTinh.isSelected()) {
            if (cboLoc.getSelectedItem() != null) {
                String gt = cboLoc.getSelectedItem().toString();
                boolean gioiTinh = false;
                if (gt.equals("Nam")) {
                    gioiTinh = true;// TODO add your handling code here:
                }
                ArrayList<NhanVien> ds = nv_dao.getListNhanVienByGioiTinh(gioiTinh);
                if (ds.size() <= 0) {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy");
                } else {
                    mdlNV.getDataVector().removeAllElements();
                    DocDuLieuVaoTable(ds);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Đang load dữ liệu.....");
            }
        } else if (rdChucVu.isSelected()) {
            if (cboLoc.getSelectedItem() != null) {
                String tenChucVu = cboLoc.getSelectedItem().toString();
                int maCV = cv_dao.getMaChucVuByTenChucVu(tenChucVu);
                ArrayList<NhanVien> dscv = nv_dao.getListNhanVienByChucVu(maCV);
                if (dscv.size() <= 0) {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy");
                } else {
                    mdlNV.getDataVector().removeAllElements();
                    DocDuLieuVaoTable(dscv);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Đang load dữ liệu.....");
            }
        }
    }//GEN-LAST:event_cboLocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        xoaTrang();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateNgaySinhPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateNgaySinhPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNgaySinhPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiemNhanVien().setVisible(true);
            }
        });
    }

    public void loadChucVu() {
        String flag = "";
        dsnv = nv_dao.getAllNV();
        for (NhanVien nhanVien : dsnv) {
            if (!(cv_dao.getTenChucVuByMaChucVu(nhanVien.getChucVu())).equals(flag)) {
                flag = cv_dao.getTenChucVuByMaChucVu(nhanVien.getChucVu());
                cboLoc.addItem(flag);

            }

        }

    }

    private void xoaTrang() {
        txtTenNV.setText("");
        txtSDT.setText("");
        txtdiaChi.setText("");
        dateNgaySinh.setDate(null);
    }

    private void loadCombobox(String data) {
        cboLoc.addItem(data);
    }

    private void timNhanVienTheoTen() {
        String tenNV = txtTenNV.getText().trim();
        if (validDataTim()) {
            ArrayList<NhanVien> dsnv = nv_dao.getListNhanVienByName(tenNV);
            if (dsnv.size() <= 0) {
                JOptionPane.showMessageDialog(txtTenNV, "Không tìm thấy tên " + tenNV);
            } else {
                DocDuLieuVaoTable(dsnv);
            }
        }
    }

    private void timNhanVienTheoDiaChi() {
        String diaChi = txtdiaChi.getText().trim();
        if (validDataDiaChi()) {
            ArrayList<NhanVien> dsnv = nv_dao.getListNhanVienByDiaChi(diaChi);
            if (dsnv.size() <= 0) {
                JOptionPane.showMessageDialog(txtdiaChi, "Không tìm thấy tên " + diaChi);
            } else {
                DocDuLieuVaoTable(dsnv);
            }
        }
    }

    private void timNhanVienTheoSDT() {
        String sdt = txtSDT.getText().trim();
        if (validDataSDT()) {
            ArrayList<NhanVien> dsnv = nv_dao.getListNhanVienBySDT(sdt);
            if (dsnv.size() <= 0) {
                JOptionPane.showMessageDialog(txtSDT, "Không tìm thấy tên " + sdt);
            } else {
                DocDuLieuVaoTable(dsnv);
            }
        }
    }

    private boolean validDataTim() {
        String tenNV = txtTenNV.getText().trim();
        if (!(tenNV.length() > 0)) {
            JOptionPane.showMessageDialog(txtTenNV, "Lỗi: Tên không được để trống");
            return false;
        }
        return true;
    }

    private boolean validDataDiaChi() {
        String diaChi = txtdiaChi.getText().trim();
        if (!(diaChi.length() > 0)) {
            JOptionPane.showMessageDialog(txtdiaChi, "Lỗi: Tên không được để trống");
            return false;
        }
        return true;
    }

    private boolean validDataSDT() {
        String sdt = txtSDT.getText().trim();
        if (!(sdt.length() > 0)) {
            JOptionPane.showMessageDialog(txtSDT, "Lỗi: Tên không được để trống");
            return false;
        }
        return true;
    }

    private void DocDuLieuVaoTable(ArrayList<NhanVien> dsnv) {
        if (dsnv == null || dsnv.size() <= 0) {
            return;
        }
        //DecimalFormat df = new DecimalFormat("#,###.##" + " VND");
        for (NhanVien item : dsnv) {
            String date = formatDate((Date) item.getNgaySinh());
            String tenChucVu = cv_dao.getTenChucVuByMaChucVu(item.getChucVu());
            mdlNV.addRow(new Object[]{item.getMaNV(), item.getHoTen(), item.getDiaChi(), date, item.getSDT(),
                tenChucVu, item.getGioiTinh() == true ? "Nam" : "Nữ"});
        }
    }

    private String formatDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        return sdf.format(date);
    }

    private void resetCbo() {
        cboLoc.removeAllItems();
    }

    private void resetTable() {
        mdlNV.getDataVector().removeAllElements();
    }

    private void emptyTable() {

        for (int i = mdlNV.getRowCount() - 1; i >= 0; i--) {
            mdlNV.removeRow(i);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLoc;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTenNV;
    private javax.swing.JLabel lbdiaChi;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lbngaySinh;
    private javax.swing.JPanel pnTimKiemNhanVien;
    private javax.swing.JRadioButton rdChucVu;
    private javax.swing.JRadioButton rdGioiTinh;
    private javax.swing.JRadioButton rdTatCa;
    private javax.swing.JTable tblTimNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtdiaChi;
    // End of variables declaration//GEN-END:variables
}
